dist: bionic
language: go
os: linux

services:
  - docker

go:
  - 1.15.x
  - 1.14.x
  - tip

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

go_import_path: github.com/percona/rds_exporter

env:
  global:
    # AWS - PMM Autotest account.
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWCEHJTL35
    # AWS_SECRET_KEY
    - secure: RAMsgaq8mKT3mizvH3UvYIk90ZkB/0Thj/R0Hw+zXmReZIQTs468w9IGnXe5JYVCQKvnvOB93PfOT0N2N6Bc+I/twru/e4snQJ7upD8rFd47SMkob2LtHNElASCXdjmrHYkQPOm5q3209RZLOZhGC87CfHwExVYBUCqrO6AC6oMYWxTAPc4NJColIiyYDM8kr/uy/GoKmwK8TZInGfEajy9aiM1rY5x6qns1PpG6DUwzEWgQG35hJ9DK6BdsMBHznA9wvthWiYl90kuOmXzFnSVbCdy9f/3iRTmT+nkIxBy+iljTFdpzsH7EvfvxqTdg6mVZ1ChigbJVL+UjJ1aOZ5fvAmqAXcmzDKf48lXzgxThK97baFk9mpM0M2QJHrF57WKbQTNuPHhMj7/w395Vi0SPFwdG2WG+ecpNqLV4r8QQl3R/X8QiCXfQJ7WI9V2IPNgaIubpyjj3A1sQ6/PzrAhWgWbvwJBJHOstLEPsvWjNAiaEAG7eK9CIdhS3dy2b56p5Ea3ODORNVZTU9ePiKlaMw8xCZXGUGl8QCd0L370S5ksIAS6pBROS4aLuWEvcrVjYlQ0pb1ZHCoQlSxfWV3QWmcUwxetZZ+MLXT9vpvr/AfqOO8xUeUh8qTid73ecGc9prdFDbRwDYA2bAQVZPUG+27z/0cdwfftkb/Nz0W4=
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: 0wFWLHDYVCXM8VEf7ZjUlTIOd0y2qbLvwHAigI83MIFjgS34hx6zxT7dC20QRGdh5HBr/Q9/zri//ca3GoyYKADEjXaDqOniI3PTnjL+RyA5Jxn8IPnBjdqcxU/WGEKs0Z4k5Fv2bLb7ipm9QcLCKDxCyQfWnWe/WAckvt83OTGXbMXNTb2XdCDGAgdYqsBLbgJq07KK+jaXtNGj1+p8lHBnuK8QIwFpfusTtlyAUaLBx307/xqk1bUMuZun2IF6nWf5MhrH8Ix3VaIB+8hkoInNU4X5Cum2rkZSvTcpvJmKzHPErkEGuJYLrnYgBjUCShWjDs0VsU8DAGYwz1hdPa/m7qX8CMRiiTBeJCtdnE7KXcrwDv0eILh4bDD6F7QNkj466lwigAIHMyBUVRTFjI77C68Fsvu/xkd22eDEBdmMJfo2x18UrP3FGqvkbdmDvjjzj4oz5z5ssQZ7z2f3uhlm9EHf8zzcP5N9Kh7zZO3LKPMiCZtOf3nxgiR0JLzM1WJ2iPflAlVWS+9Yv/uKNiJYoH+cV/8B5HwC+CryenqOOAvU68nZ5y0dgpfsW8+p6WTAzIudxy5eem+VtAmg4N5XPGdwjPRcsiLb46yGzV46Zpsi/z+R3z1f/l4Rxky7YDM9kOwoLiHDUTI9hBpv6f8P7ZRp8ZTZL3jOpZAH+UY=

install:
  # install reviewdog and golangci-lint
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

script:
  - make travis

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: iKvaMZw0DANxI+6PA6xQpse4W0XZVahHCiHnO8V5KtYhyou5pLLlcVzjwoXKEA4RLsj2/a1XnU6FZcn2L0eqoyCrHQeav9NLHCLmrtaLGROdpAU+ludJjuoKS/30wQMt9kExHmSa1BNsCtFM7pVXbbs+jRclnSTOlWXsjIHkHoLcigJ/hgOl/lOYEQr7Szxkx/05HhTmFd+i3VY3LHcGyyuMpumnEOXTs3iohhgHkI++mUoYlaGj+GDLsUe4D2z9A2bl7+5XnmJmKkPSz5moLyjxVAd+fAAX3/3kxf0GgAfD9H/DU3/1moviO3/2E02q9FI7/0cKefprnOLJ2m8RyuExQiQt3GdjKZjZkWTWh/IpfMD/9JtC65NwzlxFj3ZigQxvk/AyzDLuM4pVzkPnA3aBJdYfr9tBQ39Tg3sDQSTMDvBzPn5F7nRq3n8VXBPsIFCs4t4ZvRqZJE5BDy+cUxDVxVGZK/bpAAJM99nadR9XNwUIiLIJ5xkfljg4a/obZ1W5rnMwUWmuSmpC+cKRSSMyqjVwt8hbYfvBOdGkikaa0bV7EDI+qeeaofE7ZAnbjHNnlG6hDTeP+vYTUBQJhqevFRwADbZXgnjv2Vh/EA3LMevxZtux7fCHD7vrZFMYbRYU7S1/ysC9EtvAwrg8gm0aVgzd3Za1phiBYUN+slk=
