dist: bionic
language: go

services:
  - docker

go:
  - 1.12.x
  - 1.13.x
  - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    # AWS - PMM Autotest account. TODO https://jira.percona.com/browse/PMM-4896
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWINUW4BHY
    - secure: "cIBRl4mgANxn6XPIO2SODBuNiLMraqH7yJ21vMmLUpjPxEsTGTUtlhNU/fBcb7F62SXsV3MgyahslhCU/62SyQccuICzkP4V9gtfE8GCSG4upWA5ka1CwWPFNCTQz0xU01oXkNe9V4WLbe0cRYlR4SI0b4TRZrYy5pt4WkBKEXDBn3RYqCcNEFjL9sPYTMOZKGc1mYtIJHNjwEYtv+7rAm0YRvvPmQnVeMXK2uZZcvmhxhHJfqUuKJYeyuC7CtTVh3QKdm7FpmXFVmFRFpcEQNqBwEE6W2mWnByKt/P8seBkcuVsYWAHDtN9JmbCN7/VhVm4pb/sFHuAJ3lm4PM9Q15r7GVmwEurVhNsi9S0oai/n4tbC9U63HPKLcq04UeXYp/K6tv6uGBL7+GTfFLnkG+YsM3Npj+O4NozTniX9vvvd3irbgXl8B5LzTz+/ypv4DV69eweoG1+xlME7iOrBMz/lQPDB9lIn8P9KEAiKpnnBbjJulBLVcG8j3WUqRw8rQFQA94UfqWL3g5FBxkQXoNNoRxFz0lXUA2nPw2maxQBThs4Awzg/yhm15ipAE49/wefLf+ZnEyfhOUHkQTzb7lj3RN7Mh7lfj7l6XR8YnHIkzWXXTp2sfVoDqQIVV2jRr4uBNOGIoXzXn6QEvxjy5ou0MlBbivU6usL7i0Y+yE="

script:
  - make travis
