---
instances:
  - instance: rds-aurora1
    region: us-east-1
    labels:
      node_id: /node_id/123
  - instance: rds-aurora57
    region: us-east-1
  - instance: rds-mysql56
    region: us-east-1
    labels:
      node_id: /node_id/456
  - instance: rds-mysql57
    region: us-east-1
    labels:
      node_id: /node_id/789
