---
instances:
  - instance: auth-service-db000-live
    region: eu-west-1

  - instance: auth-service-db001-live
    region: eu-west-1

  - instance: bacchus-service-db000-live
    region: eu-west-1

  - instance: box-content-service-mysql-db000-live
    region: eu-west-1

  - instance: cart-service-db000-live
    region: eu-west-1

  - instance: csi-db000-live
    region: eu-west-1

  - instance: delivery-logistics-db001-live
    region: eu-west-1

  - instance: delivery-regions-db001-live
    region: eu-west-1

  - instance: intfood-db-at000-live
    region: eu-west-1

  - instance: intfood-db-au000-live
    region: eu-west-1
