{{- range $key, $value := .Values.deployments }}
  {{- if $value.hpa }}
    {{- if $value.hpa.enabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "rds_exporter_hf.fullname" $ }}-{{ $key }}
  labels:
    app: {{ template "rds_exporter_hf.name" $ }}-{{ $key }}
    chart: {{ template "rds_exporter_hf.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tribe: {{ $.Values.tribe }}
    squad: {{ $.Values.squad }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "rds_exporter_hf.fullname" $ }}-{{ $key }}
  minReplicas: {{ $value.hpa.replicas.min }}
  maxReplicas: {{ $value.hpa.replicas.max }}
  metrics:
{{ toYaml $value.hpa.metrics | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}