{{- range $key, $value := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rds_exporter.fullname" $ }}-{{ $key }}
  labels:
    app: {{ template "rds_exporter.name" $ }}-{{ $key }}
    chart: {{ template "rds_exporter.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tribe: {{ $.Values.tribe }}
    squad: {{ $.Values.squad }}
    version: "{{ if $.Values.tag }}{{ $.Values.tag }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rds_exporter.name" $ }}-{{ $key }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rds_exporter.name" $ }}-{{ $key }}
        release: {{ $.Release.Name }}
        environment: {{ $.Values.environment }}
        tribe: {{ $.Values.tribe }}
        squad: {{ $.Values.squad }}
        version: "{{ if $.Values.tag }}{{ $.Values.tag }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
{{- if or ($.Values.podAnnotations) ($value.podAnnotations) }}
      annotations:
{{- with $.Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $value.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        # all php-fpm containers should be named "fpm" for easier metrics gathering
        {{ if and $value.phpFPMMetricsExporter }}
        - name: {{ if $value.phpFPMMetricsExporter.enabled }}fpm{{ else }}{{ $.Chart.Name }}-{{ $key }}{{ end }}
        {{- else }}
        - name:  {{ $.Chart.Name }}-{{ $key }}
        {{- end }}
          {{- if $.Values.tag }}
          image: "{{ $value.repository }}:{{ $.Values.tag }}"
          {{- else }}
          image: "{{ $value.repository }}:{{ $.Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ $value.pullPolicy }}
          {{- if $value.command }}
          command: {{ $value.command }}
          {{- end }}
          {{- if $value.args }}
          args:
{{ toYaml $value.args | indent 12 }}
          {{- end }}
          env:
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- if $value.env }}
          {{- range $envName, $envValue := $value.env }}
          - name: {{ $envName }}
            value: {{ $envValue | quote }}
          {{- end }}
          {{- end }}
          {{- if or ($.Values.configMap) ($.Values.secrets) }}
          envFrom:
          {{- if $.Values.configMap }}
            - configMapRef:
                name: {{ template "rds_exporter.fullname" $ }}
          {{- end }}
          {{- if $.Values.secrets }}
            - secretRef:
                name: {{ template "rds_exporter.fullname" $ }}
          {{- end }}
          {{- end }}
          {{- if $value.containerPort }}
          ports:
            - name: http
              containerPort: {{ $value.containerPort }}
              protocol: TCP
          {{- end }}
          {{- with $value.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $value.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          resources:
{{ toYaml $value.resources | indent 12 }}
        {{- if $value.phpFPMMetricsExporter }}
          {{- if $value.phpFPMMetricsExporter.enabled }}
        - name: "php-fpm-exporter"
          image: "{{ $value.phpFPMMetricsExporter.repository }}:{{ $value.phpFPMMetricsExporter.tag }}"
          imagePullPolicy: {{ $value.pullPolicy }}
          ports:
            - name: {{ $value.phpFPMMetricsExporter.portName }}
              containerPort: {{ $value.phpFPMMetricsExporter.tcpPort }}
              protocol: TCP
          {{- end }}
        {{- end }}
    {{- with $value.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $value.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $value.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
