{{- range $key, $job := .Values.cronJobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $.Release.Name }}-{{ $key }}"
  labels:
    app: {{ template "rds-exporter.name" $ }}-{{ $key }}
    chart: {{ template "rds-exporter.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tribe: {{ $.Values.tribe }}
    squad: {{ $.Values.squad }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "rds-exporter.name" $ }}-{{ $key }}
            cron: {{ $key }}
{{- with $.Values.podAnnotations }}
          annotations:
{{ toYaml . | indent 12 }}
{{- end }}
        spec:
          containers:
          - name: {{ $key }}
            {{- if $.Values.tag }}
            image: "{{ $job.repository }}:{{ $.Values.tag }}"
            {{- else }}
            image: "{{ $job.repository }}:{{ $.Chart.AppVersion }}"
            {{- end }}
            imagePullPolicy: {{ $job.pullPolicy }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- if $job.args }}
            args:
{{ toYaml $job.args | indent 14 }}
            {{- end }}
            {{- if or ($.Values.configMap) ($.Values.secrets) }}
            envFrom:
            {{- if $.Values.configMap }}
              - configMapRef:
                  name: {{ template "rds-exporter.fullname" $ }}
            {{- end }}
            {{- if $.Values.secrets }}
              - secretRef:
                  name: {{ template "rds-exporter.fullname" $ }}
            {{- end }}
            {{- end }}
          restartPolicy: OnFailure

  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  {{- end }}
