name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.15
          - 1.16
        include:
          - go-version: tip
            os: ubuntu-latest
            may-fail: true
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: percona-platform/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: percona-platform/checkout@v2
    - name: Run Build
      run: make build
    - name: Run checks/linters
      run: make ci-reviewdog
    - name: Run test
      run: make test-race
    - name: Run Codeconv
      run: make codecov
    - name: Build tarball
      run: make tarball
    - name: Build tarball
      run: make docker
    - name: Run debug commands on failure
      if: ${{ failure() }}
      run: |
        env
        go version
        go env
        pwd
        git status
